name: dentease
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  uuid: ^4.2.1
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.2.1
  timeago: ^3.1.0
  google_maps_flutter: ^2.11.0
  http: ^0.13.6
  provider: ^6.0.3
  geolocator: 13.0.2
  table_calendar: ^3.0.9
  meta: 1.16.0
  flutter:
    sdk: flutter
  tflite_flutter: ^0.12.1
  image: ^3.3.0

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.3
  image_picker: ^0.8.9
  chat_supabase: ^1.1.0
  geocoding: ^3.0.0
  camera: ^0.10.5+9
  path_provider: ^2.0.11
  path: ^1.8.3
  intl: ^0.19.0
  shared_preferences: ^2.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash_background.png
    - assets/background1.png
    - assets/background2.png
    - assets/logo.png
    - assets/logo2.png
    - assets/icons/scan.png
    - assets/icons/chat.png
    - assets/icons/calendar.png
    - assets/icons/profile.png
    - assets/icons/home.png
    - assets/icons/customer-service.png
    - assets/profile.png
    - assets/clinic1.png
    - assets/clinic2.png
    - assets/clinic3.png
    - assets/sample_disease.png
    - assets/upload.jpg
    - assets/model.tflite
    - assets/teeth_validator.tflite
    - assets/labels.txt
    - assets/validator_labels.txt
    - assets/disease_labels.txt
    - assets/apk-logo.png
    - assets/nearby.png
    - assets/dentist/dentist.png
    - assets/dentist/analysis.png
    - assets/dentist/calendar.png
    - assets/dentist/details.png
    - assets/dentist/patient.png
    - assets/dentist/services.png
    - assets/dentist/staff.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/apk-logo.png"
